apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  backoffLimit: 3
  ttlSecondsAfterFinish: 300
  template:
    spec:
      containers:
        - name: backend
          image: sale-app-backend:latest
          command: ["python", "manage.py", "migrate"]
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
      restartPolicy: Never
