name: CI/CD Pipeline
on:
  push:
     branches: ["master"]
jobs:
    build-and-deploy:
      runs-on: self-hosted
      steps: 
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: kind create cluster
          run: |
            kind create cluster --name sale-cluster --config kind-config.yaml

        - name: Docker build image
          run: |
            docker build -t sale-app-backend:latest ./backend
            docker build -t sale-app-frontend:latest ./frontend

        - name: Load docker-image
          run: |
            kind load docker-image sale-app-backend:latest --name sale-cluster
            kind load docker-image sale-app-frontend:latest --name sale-cluster

        - name: Kubectl apply 
          run: |
            kubectl apply -f k8s/

        - name: wait for postgres
          run: |
            kubectl rollout status deployment/postgres-deployment

        - name: wait for backend
          run: |
            kubectl rollout status deployment/backend-deployment

        - name: Django migrate
          run: |
            kubectl delete job migrate --ignore-not-found 
            kubectl apply -f k8s/jobs/migrate.yaml
            kubectl wait --for=condition=complete job/django-migrate --timeout=70s